apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup
spec:
  schedule: "* 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 100
            runAsGroup: 101
            fsGroup: 101
          containers:
            - name: pg-backup
              image: ghcr.io/la-cc/k8s-pg-to-s3-cronjob:latest
              env:
              - name: HOME
                value: /tmp
              envFrom:
                - secretRef:
                    name: pg-backup-secrets
                - configMapRef:
                    name: pg-backup-config
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"
                limits:
                  memory: "256Mi"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                privileged: false
                capabilities:
                  drop:
                    - ALL
          restartPolicy: OnFailure
